-- Generated from the current Vidferry SQLite schema.

CREATE TABLE IF NOT EXISTS schema_migrations (
    version INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    checksum TEXT NOT NULL,
    applied_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_settings (
        key TEXT PRIMARY KEY,
        value TEXT NOT NULL,
        updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE user_info (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        type INTEGER NOT NULL,
        filePath TEXT NOT NULL,
        userName TEXT NOT NULL,
        status INTEGER DEFAULT 0
    );

CREATE TABLE file_records (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        asset_id TEXT,
        filename TEXT NOT NULL,
        original_filename TEXT,
        filesize DOUBLE PRECISION,
        upload_time TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        file_path TEXT,
        storage_key TEXT,
        storage_backend TEXT DEFAULT 'local',
        source_type TEXT DEFAULT 'manual_upload',
        source_video_id TEXT,
        status TEXT DEFAULT 'ready',
        duration TEXT,
        duration_seconds DOUBLE PRECISION DEFAULT 0,
        metadata TEXT DEFAULT '{}'
    );

CREATE TABLE auth_users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username TEXT NOT NULL UNIQUE,
        display_name TEXT NOT NULL, password_hash TEXT NOT NULL, role TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'active', must_change_password INTEGER NOT NULL DEFAULT 1,
        password_changed_at TIMESTAMP WITHOUT TIME ZONE, created_by INTEGER, failed_login_count INTEGER NOT NULL DEFAULT 0,
        locked_until TIMESTAMP WITHOUT TIME ZONE, last_login_at TIMESTAMP WITHOUT TIME ZONE, created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
    );

CREATE TABLE agent_sessions (
        id TEXT PRIMARY KEY,
        title TEXT,
        context TEXT DEFAULT '{}',
        summary TEXT DEFAULT '{}',
        summary_through_id INTEGER DEFAULT 0,
        message_count INTEGER DEFAULT 0,
        deleted_at TIMESTAMP WITHOUT TIME ZONE,
        created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
    , owner_user_id INTEGER);

CREATE TABLE agent_session_locks (
        session_id TEXT PRIMARY KEY,
        owner_id TEXT NOT NULL,
        expires_at DOUBLE PRECISION NOT NULL
    );

CREATE TABLE agent_rules (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        category TEXT NOT NULL,
        severity TEXT NOT NULL,
        pattern TEXT,
        description TEXT,
        enabled INTEGER DEFAULT 1,
        created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE agent_memory_items (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        memory_type TEXT NOT NULL,
        title TEXT,
        content TEXT NOT NULL,
        metadata TEXT DEFAULT '{}',
        created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE agent_messages (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        session_id TEXT NOT NULL,
        role TEXT NOT NULL,
        content TEXT NOT NULL,
        context TEXT DEFAULT '{}',
        created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE agent_runs (
        id TEXT PRIMARY KEY,
        session_id TEXT,
        run_type TEXT NOT NULL,
        subject_type TEXT DEFAULT '',
        subject_id TEXT DEFAULT '',
        status TEXT DEFAULT 'success',
        decision TEXT,
        severity TEXT,
        content_hash TEXT,
        input_summary TEXT DEFAULT '{}',
        output TEXT DEFAULT '{}',
        model TEXT,
        duration_ms INTEGER DEFAULT 0,
        created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE youtube_video_groups (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL UNIQUE,
        is_default INTEGER NOT NULL DEFAULT 0 CHECK (is_default IN (0, 1)),
        created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE youtube_videos (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        video_id TEXT UNIQUE NOT NULL,
        title TEXT,
        channel TEXT,
        subscribers TEXT,
        published_at TEXT,
        url TEXT NOT NULL,
        thumbnail TEXT,
        duration TEXT,
        query TEXT,
        download_status INTEGER DEFAULT 0,
        publish_status INTEGER DEFAULT 0,
        translate_status INTEGER DEFAULT 0,
        downloaded_file_path TEXT,
        processed_file_path TEXT,
        transcript_status INTEGER DEFAULT 0,
        transcript_file_path TEXT,
        transcript_language TEXT,
        analysis_status INTEGER DEFAULT 0,
        analysis_result TEXT,
        publish_draft TEXT,
        analysis_updated_at TIMESTAMP WITHOUT TIME ZONE,
        group_id INTEGER,
        created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(group_id) REFERENCES youtube_video_groups(id) ON DELETE RESTRICT
    );

CREATE TABLE youtube_search_jobs (
        id TEXT PRIMARY KEY,
        query TEXT NOT NULL,
        requested INTEGER NOT NULL,
        found INTEGER DEFAULT 0,
        created_count INTEGER DEFAULT 0,
        duplicate_count INTEGER DEFAULT 0,
        skipped_count INTEGER DEFAULT 0,
        failed_count INTEGER DEFAULT 0,
        status TEXT NOT NULL,
        message TEXT,
        source TEXT,
        group_id INTEGER,
        group_name_snapshot TEXT,
        duration_min_seconds INTEGER,
        duration_max_seconds INTEGER,
        duration_filtered_count INTEGER DEFAULT 0,
        started_at TIMESTAMP WITHOUT TIME ZONE,
        finished_at TIMESTAMP WITHOUT TIME ZONE,
        created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
    );

CREATE TABLE youtube_search_job_items (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        job_id TEXT NOT NULL,
        ordinal INTEGER NOT NULL,
        video_id TEXT,
        title TEXT,
        decision TEXT NOT NULL,
        error TEXT,
        created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(job_id, ordinal),
        FOREIGN KEY(job_id) REFERENCES youtube_search_jobs(id) ON DELETE CASCADE
    );

CREATE TABLE youtube_workflow_jobs (
        id TEXT PRIMARY KEY,
        video_id TEXT,
        url TEXT NOT NULL,
        account TEXT,
        channel TEXT,
        subscribers TEXT,
        published_at TEXT,
        bilibili_account TEXT,
        bilibili_tid INTEGER DEFAULT 249,
        xiaohongshu_account TEXT,
        kuaishou_account TEXT,
        tencent_account TEXT,
        publish_to_douyin INTEGER DEFAULT 1,
        publish_to_bilibili INTEGER DEFAULT 0,
        publish_to_xiaohongshu INTEGER DEFAULT 0,
        publish_to_kuaishou INTEGER DEFAULT 0,
        publish_to_tencent INTEGER DEFAULT 0,
        process_version TEXT DEFAULT 'translation_v1',
        subtitle_language TEXT DEFAULT 'zh-CN',
        burn_profile TEXT DEFAULT 'stable',
        subtitle_size TEXT DEFAULT 'large',
        translator_label TEXT DEFAULT 'Vidferry翻译',
        watermark_enabled INTEGER DEFAULT 0,
        watermark_text TEXT DEFAULT '',
        cover_title TEXT DEFAULT '',
        cover_context TEXT DEFAULT '',
        cover_brand_name TEXT DEFAULT '',
        cover_brand_platform TEXT DEFAULT '',
        title TEXT,
        description TEXT,
        tags TEXT,
        schedule TEXT,
        status TEXT NOT NULL,
        step TEXT,
        message TEXT,
        source_file_path TEXT,
        processed_file_path TEXT,
        publish_command TEXT,
        publish_confirmation_required INTEGER DEFAULT 0,
        publish_confirmation_status TEXT DEFAULT '',
        content_risk TEXT DEFAULT '{}',
        progress DOUBLE PRECISION DEFAULT 0,
        speed TEXT,
        eta TEXT,
        created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        started_at TIMESTAMP WITHOUT TIME ZONE,
        updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
    , error_code TEXT, error_type TEXT, error_reason TEXT, error_detail TEXT, interrupted_at TIMESTAMP WITHOUT TIME ZONE, warning_code TEXT DEFAULT '', highlight_count INTEGER DEFAULT 3);

CREATE TABLE youtube_workflow_locks (
        video_id TEXT NOT NULL,
        scope TEXT NOT NULL,
        job_id TEXT NOT NULL UNIQUE,
        created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (video_id, scope)
    );

CREATE TABLE youtube_workflow_events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        job_id TEXT NOT NULL,
        video_id TEXT,
        stage TEXT NOT NULL,
        stage_label TEXT,
        status TEXT DEFAULT 'running',
        message TEXT,
        input_file_path TEXT,
        output_file_path TEXT,
        input_size_mb DOUBLE PRECISION DEFAULT 0,
        output_size_mb DOUBLE PRECISION DEFAULT 0,
        started_at TIMESTAMP WITHOUT TIME ZONE,
        ended_at TIMESTAMP WITHOUT TIME ZONE,
        duration_seconds DOUBLE PRECISION DEFAULT 0,
        cloud_model TEXT,
        prompt_tokens INTEGER DEFAULT 0,
        completion_tokens INTEGER DEFAULT 0,
        total_tokens INTEGER DEFAULT 0,
        cloud_latency_ms DOUBLE PRECISION DEFAULT 0,
        metadata TEXT DEFAULT '{}',
        created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE youtube_workflow_llm_usage_events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        workflow_event_id INTEGER,
        job_id TEXT NOT NULL,
        video_id TEXT,
        stage TEXT,
        operation TEXT,
        provider TEXT,
        model TEXT,
        status TEXT NOT NULL DEFAULT 'success',
        attempt INTEGER NOT NULL DEFAULT 1,
        prompt_tokens INTEGER NOT NULL DEFAULT 0,
        completion_tokens INTEGER NOT NULL DEFAULT 0,
        total_tokens INTEGER NOT NULL DEFAULT 0,
        latency_ms DOUBLE PRECISION NOT NULL DEFAULT 0,
        error_message TEXT,
        error_category TEXT,
        violations TEXT,
        raw_output TEXT,
        created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE youtube_subtitle_audits (
        job_id TEXT PRIMARY KEY,
        video_id TEXT,
        video_title TEXT,
        target_language TEXT,
        initial_segments TEXT NOT NULL DEFAULT '[]',
        reviewed_segments TEXT NOT NULL DEFAULT '[]',
        review_status TEXT NOT NULL DEFAULT 'unknown',
        fallback_segment_count INTEGER NOT NULL DEFAULT 0,
        review_batches TEXT NOT NULL DEFAULT '[]',
        saved_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE published_youtube_materials (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        video_id TEXT,
        source_url TEXT,
        title TEXT,
        platform TEXT,
        platform_type INTEGER DEFAULT 0,
        account_file TEXT,
        account_count INTEGER DEFAULT 0,
        material_id INTEGER,
        filename TEXT,
        file_path TEXT,
        filesize DOUBLE PRECISION DEFAULT 0,
        thumbnail TEXT,
        channel TEXT,
        subscribers TEXT,
        source_published_at TEXT,
        publish_title TEXT,
        metadata TEXT DEFAULT '{}',
        published_at TIMESTAMP WITHOUT TIME ZONE,
        created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
    , publish_task_id TEXT, status TEXT DEFAULT 'success', message TEXT, duration_ms INTEGER DEFAULT 0, account_name TEXT, deleted_at TIMESTAMP WITHOUT TIME ZONE, updated_at TIMESTAMP WITHOUT TIME ZONE);

CREATE TABLE scheduled_publish_tasks (
        id TEXT PRIMARY KEY, video_id TEXT NOT NULL, material_id INTEGER NOT NULL, file_path TEXT NOT NULL,
        scheduled_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, status TEXT NOT NULL DEFAULT 'pending', overdue INTEGER NOT NULL DEFAULT 0,
        message TEXT, risk_override TEXT DEFAULT '{}', created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, started_at TIMESTAMP WITHOUT TIME ZONE,
        finished_at TIMESTAMP WITHOUT TIME ZONE, canceled_at TIMESTAMP WITHOUT TIME ZONE, updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
    );

CREATE TABLE scheduled_publish_targets (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, task_id TEXT NOT NULL, platform_type INTEGER NOT NULL,
        account_id INTEGER, account_name TEXT, settings TEXT NOT NULL DEFAULT '{}', status TEXT NOT NULL DEFAULT 'pending',
        message TEXT, duration_ms INTEGER NOT NULL DEFAULT 0, started_at TIMESTAMP WITHOUT TIME ZONE, finished_at TIMESTAMP WITHOUT TIME ZONE,
        updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, FOREIGN KEY(task_id) REFERENCES scheduled_publish_tasks(id) ON DELETE CASCADE
    );

CREATE TABLE auth_sessions (
        token_hash TEXT PRIMARY KEY, user_id INTEGER NOT NULL, created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        last_seen_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, idle_expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        absolute_expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, ip_address TEXT, user_agent TEXT, revoked_at TIMESTAMP WITHOUT TIME ZONE,
        FOREIGN KEY(user_id) REFERENCES auth_users(id) ON DELETE CASCADE
    );

CREATE TABLE auth_audit_logs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, actor_user_id INTEGER, action TEXT NOT NULL,
        target_type TEXT, target_id TEXT, result TEXT NOT NULL, ip_address TEXT, user_agent TEXT,
        details TEXT NOT NULL DEFAULT '{}', created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        FOREIGN KEY(actor_user_id) REFERENCES auth_users(id) ON DELETE SET NULL
    );

CREATE TABLE feishu_butler_notifications (
        fingerprint TEXT PRIMARY KEY,
        kind TEXT NOT NULL,
        subject_id TEXT NOT NULL,
        state TEXT NOT NULL,
        target_open_id TEXT NOT NULL,
        summary TEXT NOT NULL DEFAULT '',
        delivery_state TEXT NOT NULL DEFAULT 'pending',
        attempt_count INTEGER NOT NULL DEFAULT 0,
        last_attempt_at TIMESTAMP WITHOUT TIME ZONE,
        last_attempt_epoch DOUBLE PRECISION NOT NULL DEFAULT 0,
        sent_at TIMESTAMP WITHOUT TIME ZONE,
        last_error TEXT DEFAULT '',
        created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE youtube_video_deletions (
        video_id TEXT PRIMARY KEY,
        deleted_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
    );

CREATE INDEX idx_agent_memory_type ON agent_memory_items(memory_type, updated_at);

CREATE INDEX idx_agent_messages_session ON agent_messages(session_id, id);

CREATE INDEX idx_agent_rules_enabled ON agent_rules(enabled, category);

CREATE INDEX idx_agent_runs_hash ON agent_runs(content_hash, run_type);

CREATE INDEX idx_agent_runs_session ON agent_runs(session_id, created_at);

CREATE INDEX idx_agent_runs_subject ON agent_runs(run_type, subject_type, subject_id, created_at DESC);

CREATE INDEX idx_agent_session_locks_expiry ON agent_session_locks(expires_at);

CREATE INDEX idx_agent_sessions_updated ON agent_sessions(deleted_at, updated_at DESC);

CREATE INDEX idx_auth_audit_created ON auth_audit_logs(created_at DESC, id DESC);

CREATE INDEX idx_auth_sessions_user ON auth_sessions(user_id, revoked_at);

CREATE INDEX idx_feishu_butler_pending ON feishu_butler_notifications(delivery_state, last_attempt_at);

CREATE INDEX idx_feishu_butler_subject ON feishu_butler_notifications(kind, subject_id);

CREATE UNIQUE INDEX idx_file_records_asset_id ON file_records(asset_id);

CREATE INDEX idx_file_records_source_type ON file_records(source_type);

CREATE INDEX idx_file_records_source_type_upload ON file_records(source_type, upload_time, id);

CREATE INDEX idx_file_records_source_video_id ON file_records(source_video_id);

CREATE INDEX idx_file_records_status_upload ON file_records(status, upload_time DESC, id DESC);

CREATE INDEX idx_file_records_upload_order ON file_records(upload_time DESC, id DESC);

CREATE INDEX idx_file_records_video_type ON file_records(source_video_id, source_type);

CREATE INDEX idx_published_youtube_materials_published_at ON published_youtube_materials(published_at);

CREATE INDEX idx_published_youtube_materials_source_url ON published_youtube_materials(source_url);

CREATE INDEX idx_published_youtube_materials_status ON published_youtube_materials(status, deleted_at);

CREATE INDEX idx_published_youtube_materials_task ON published_youtube_materials(publish_task_id, deleted_at);

CREATE INDEX idx_published_youtube_materials_updated ON published_youtube_materials(updated_at, id);

CREATE INDEX idx_published_youtube_materials_video_id ON published_youtube_materials(video_id);

CREATE UNIQUE INDEX idx_published_youtube_materials_video_platform
    ON published_youtube_materials(video_id, platform_type)
    WHERE video_id IS NOT NULL AND video_id != ''
      AND platform_type IS NOT NULL AND platform_type != 0
      AND deleted_at IS NULL
    ;

CREATE INDEX idx_scheduled_publish_targets_task ON scheduled_publish_targets(task_id, id);

CREATE INDEX idx_scheduled_publish_tasks_due ON scheduled_publish_tasks(status, scheduled_at);

CREATE INDEX idx_subtitle_audits_saved ON youtube_subtitle_audits(saved_at DESC);

CREATE INDEX idx_subtitle_audits_video_saved ON youtube_subtitle_audits(video_id, saved_at DESC);

CREATE INDEX idx_workflow_llm_usage_event ON youtube_workflow_llm_usage_events(workflow_event_id, id);

CREATE INDEX idx_workflow_llm_usage_job ON youtube_workflow_llm_usage_events(job_id, created_at DESC, id DESC);

CREATE INDEX idx_workflow_llm_usage_model_time ON youtube_workflow_llm_usage_events(model, created_at, id);

CREATE INDEX idx_youtube_search_job_items_job ON youtube_search_job_items(job_id, ordinal);

CREATE UNIQUE INDEX idx_youtube_search_job_items_video
    ON youtube_search_job_items(job_id, video_id)
    WHERE video_id IS NOT NULL AND video_id != ''
    ;

CREATE INDEX idx_youtube_search_jobs_group_status ON youtube_search_jobs(group_id, status);

CREATE INDEX idx_youtube_search_jobs_status ON youtube_search_jobs(status, created_at);

CREATE UNIQUE INDEX idx_youtube_video_groups_default
    ON youtube_video_groups(is_default) WHERE is_default = 1
    ;

CREATE INDEX idx_youtube_videos_analysis_status ON youtube_videos(analysis_status);

CREATE INDEX idx_youtube_videos_created ON youtube_videos(created_at, id);

CREATE INDEX idx_youtube_videos_download_status ON youtube_videos(download_status);

CREATE INDEX idx_youtube_videos_group_created ON youtube_videos(group_id, created_at DESC, id DESC);

CREATE INDEX idx_youtube_videos_publish_status ON youtube_videos(publish_status);

CREATE INDEX idx_youtube_videos_translate_status ON youtube_videos(translate_status);

CREATE INDEX idx_youtube_workflow_events_job_id ON youtube_workflow_events(job_id);

CREATE INDEX idx_youtube_workflow_events_job_started ON youtube_workflow_events(job_id, started_at DESC, id DESC);

CREATE INDEX idx_youtube_workflow_events_stage ON youtube_workflow_events(stage);

CREATE INDEX idx_youtube_workflow_events_started ON youtube_workflow_events(started_at, id);

CREATE INDEX idx_youtube_workflow_events_video_id ON youtube_workflow_events(video_id);

CREATE INDEX idx_youtube_workflow_jobs_status ON youtube_workflow_jobs(status);

CREATE INDEX idx_youtube_workflow_jobs_status_updated ON youtube_workflow_jobs(status, updated_at, created_at);

CREATE INDEX idx_youtube_workflow_jobs_video_id ON youtube_workflow_jobs(video_id);

CREATE INDEX idx_youtube_workflow_jobs_video_status_updated ON youtube_workflow_jobs(video_id, status, updated_at DESC, created_at DESC);

CREATE INDEX idx_youtube_workflow_jobs_video_updated ON youtube_workflow_jobs(video_id, updated_at, created_at);

CREATE INDEX idx_youtube_workflow_locks_job_id ON youtube_workflow_locks(job_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_youtube_video_groups_name_ci ON youtube_video_groups(lower(name));
