CREATE TABLE IF NOT EXISTS app_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_type TEXT NOT NULL,
    severity TEXT NOT NULL DEFAULT 'warning',
    aggregate_key TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    action_route TEXT NOT NULL DEFAULT '{}',
    source_refs TEXT NOT NULL DEFAULT '[]',
    occurrence_count INTEGER NOT NULL DEFAULT 1,
    status TEXT NOT NULL DEFAULT 'active',
    source_active INTEGER NOT NULL DEFAULT 1,
    manual_resolved INTEGER NOT NULL DEFAULT 0,
    first_seen_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    acknowledged_at TIMESTAMP WITHOUT TIME ZONE,
    resolved_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_app_notifications_status_updated
    ON app_notifications(status, updated_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_app_notifications_source_active
    ON app_notifications(source_active, notification_type);
