CREATE TABLE IF NOT EXISTS publish_dispatch_jobs (
    id TEXT PRIMARY KEY,
    source TEXT NOT NULL,
    source_ref_id TEXT NOT NULL DEFAULT '',
    owner_user_id BIGINT,
    video_id TEXT NOT NULL,
    material_id BIGINT,
    payload TEXT NOT NULL DEFAULT '{}',
    status TEXT NOT NULL DEFAULT 'pending',
    message TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP WITHOUT TIME ZONE,
    finished_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS publish_dispatch_targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id TEXT NOT NULL REFERENCES publish_dispatch_jobs(id) ON DELETE CASCADE,
    platform_type INTEGER NOT NULL,
    account_id BIGINT,
    status TEXT NOT NULL DEFAULT 'pending',
    message TEXT NOT NULL DEFAULT '',
    duration_ms INTEGER NOT NULL DEFAULT 0,
    settings TEXT NOT NULL DEFAULT '{}',
    started_at TIMESTAMP WITHOUT TIME ZONE,
    finished_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (job_id, platform_type)
);

CREATE INDEX IF NOT EXISTS idx_publish_dispatch_jobs_state
    ON publish_dispatch_jobs(status, created_at, id);

CREATE INDEX IF NOT EXISTS idx_publish_dispatch_jobs_source
    ON publish_dispatch_jobs(source, source_ref_id);

CREATE INDEX IF NOT EXISTS idx_publish_dispatch_jobs_owner
    ON publish_dispatch_jobs(owner_user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_publish_dispatch_targets_job
    ON publish_dispatch_targets(job_id, id);
