CREATE TABLE short_video_projects (
    id TEXT PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    topic TEXT NOT NULL,
    target_count INTEGER NOT NULL DEFAULT 10,
    target_duration_seconds INTEGER NOT NULL DEFAULT 45,
    transition_type TEXT NOT NULL DEFAULT 'cut',
    bgm_track_id BIGINT,
    keep_original_audio INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'draft',
    message TEXT DEFAULT '',
    output_file_path TEXT DEFAULT '',
    output_material_id BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE short_video_candidates (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES short_video_projects(id) ON DELETE CASCADE,
    source_video_id TEXT NOT NULL,
    source_url TEXT NOT NULL,
    title TEXT DEFAULT '',
    channel TEXT DEFAULT '',
    license_type TEXT DEFAULT '',
    license_basis TEXT DEFAULT '',
    duration_seconds DOUBLE PRECISION DEFAULT 0,
    width INTEGER DEFAULT 0,
    height INTEGER DEFAULT 0,
    thumbnail TEXT DEFAULT '',
    metadata_status TEXT NOT NULL DEFAULT 'accepted',
    analysis_status TEXT NOT NULL DEFAULT 'pending',
    analysis_score INTEGER DEFAULT 0,
    analysis_reason TEXT DEFAULT '',
    preview_path TEXT DEFAULT '',
    keyframes TEXT DEFAULT '[]',
    selected INTEGER NOT NULL DEFAULT 0,
    ordinal INTEGER NOT NULL DEFAULT 0,
    clip_duration_seconds DOUBLE PRECISION DEFAULT 0,
    transition_type TEXT DEFAULT '',
    downloaded_file_path TEXT DEFAULT '',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    UNIQUE(project_id, source_video_id)
);

CREATE TABLE short_video_bgm_tracks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    artist TEXT NOT NULL,
    source_url TEXT NOT NULL,
    license_note TEXT NOT NULL,
    file_path TEXT NOT NULL,
    enabled INTEGER NOT NULL DEFAULT 1,
    created_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE short_video_channel_whitelist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel TEXT NOT NULL UNIQUE,
    note TEXT DEFAULT '',
    created_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE INDEX idx_short_video_projects_owner_updated ON short_video_projects(owner_user_id, updated_at DESC);
CREATE INDEX idx_short_video_candidates_project_ordinal ON short_video_candidates(project_id, ordinal);
