ALTER TABLE auth_sessions
    ADD COLUMN IF NOT EXISTS remembered INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS auth_identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES auth_users(id) ON DELETE CASCADE,
    provider TEXT NOT NULL,
    subject_hash TEXT NOT NULL,
    verified_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    UNIQUE(provider, subject_hash)
);

CREATE TABLE IF NOT EXISTS auth_phone_challenges (
    id TEXT PRIMARY KEY,
    phone_hash TEXT NOT NULL,
    code_hash TEXT NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 5,
    expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    consumed_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS auth_rate_limit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope TEXT NOT NULL,
    key_hash TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_auth_identities_user
    ON auth_identities(user_id, provider);

CREATE INDEX IF NOT EXISTS idx_auth_phone_challenges_lookup
    ON auth_phone_challenges(phone_hash, expires_at);

CREATE INDEX IF NOT EXISTS idx_auth_rate_limit_lookup
    ON auth_rate_limit_events(scope, key_hash, created_at);
