ALTER TABLE agent_sessions
    ADD COLUMN IF NOT EXISTS summary_version INTEGER NOT NULL DEFAULT 1;

ALTER TABLE agent_sessions
    ADD COLUMN IF NOT EXISTS summary_updated_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE agent_sessions
    ADD COLUMN IF NOT EXISTS context_policy_version TEXT NOT NULL DEFAULT 'agent-context-v2';

ALTER TABLE agent_sessions
    ADD COLUMN IF NOT EXISTS last_compaction_run_id TEXT NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS agent_turn_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES agent_sessions(id) ON DELETE CASCADE,
    turn_id BIGINT,
    sequence INTEGER NOT NULL,
    event_type TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT '',
    tool_name TEXT NOT NULL DEFAULT '',
    payload TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_agent_turn_events_session_turn
    ON agent_turn_events(session_id, turn_id, sequence, id);
