"""SQLite SQL 到 PostgreSQL 的最小兼容适配。"""

from collections.abc import Mapping
import re


class HybridRow(Mapping):
    """同时支持 SQLite Row 的下标和字段名访问。"""

    def __init__(self, columns, values):
        self._columns = tuple(columns)
        self._values = tuple(values)
        self._by_name = dict(zip(self._columns, self._values))

    def __getitem__(self, key):
        return self._values[key] if isinstance(key, int) else self._by_name[key]

    def __iter__(self):
        return iter(self._values)

    def __len__(self):
        return len(self._values)

    def keys(self):
        return self._columns


def _replace_placeholders(sql):
    parts, quoted, quote = [], False, ""
    for char in sql:
        if char in "'\"":
            if not quoted:
                quoted, quote = True, char
            elif quote == char:
                quoted = False
        parts.append("%s" if char == "?" and not quoted else char)
    return "".join(parts)


def normalize_postgres_sql(sql):
    """转换项目当前使用的 SQLite 方言；业务 SQL 仍应逐步显式改写。"""
    value = str(sql or "")
    value = re.sub(r"\bBEGIN\s+IMMEDIATE\b", "BEGIN", value, flags=re.I)
    value = re.sub(r"\bINSERT\s+OR\s+IGNORE\b", "INSERT", value, flags=re.I)
    if re.match(r"^\s*INSERT\s+INTO\b", value, re.I) and "ON CONFLICT" not in value.upper():
        value += " ON CONFLICT DO NOTHING" if "INSERT OR IGNORE" in str(sql).upper() else ""
    value = re.sub(r"json_extract\(([^,]+),\s*'\$\.([A-Za-z_][\w]*)'\)", r"CAST(\1 AS jsonb) ->> '\2'", value, flags=re.I)
    value = re.sub(r"datetime\('now',\s*'-(\d+) minutes'\)", r"CURRENT_TIMESTAMP - INTERVAL '\1 minutes'", value, flags=re.I)
    value = re.sub(r"datetime\(([^)]+)\)", r"\1", value, flags=re.I)
    value = re.sub(r"strftime\(([^,]+),\s*([^)]+)\)", r"to_char(\2, \1)", value, flags=re.I)
    value = re.sub(r"INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT", "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", value, flags=re.I)
    value = re.sub(r"\bDATETIME\b", "TIMESTAMP WITHOUT TIME ZONE", value, flags=re.I)
    value = re.sub(r"\bREAL\b", "DOUBLE PRECISION", value, flags=re.I)
    value = re.sub(r"\s+COLLATE\s+NOCASE", "", value, flags=re.I)
    value = re.sub(r"\bLIKE\b", "ILIKE", value, flags=re.I)
    return _replace_placeholders(value)


def normalize_postgres_params(sql, params):
    """PostgreSQL 的 to_char 格式符与 SQLite strftime 格式符对齐。"""
    if not re.search(r"strftime\s*\(", str(sql), re.I):
        return params
    formats = {"%Y": "YYYY", "%m": "MM", "%d": "DD", "%H": "HH24", "%M": "MI", "%S": "SS"}
    converted = []
    for value in params:
        text = value
        if isinstance(value, str):
            for source, target in formats.items():
                text = text.replace(source, target)
        converted.append(text)
    return tuple(converted)
